In [2]:
#Варіант 4, Давидов Євген Денисович, ФІТ-4-6
import numpy as np

In [3]:
# Завдання 1: Створіть одновимірний масив (вектор) з непарними числами від 1 до 19 та виведіть його значення.

In [4]:
vect = np.arange(1, 20)
print(vect)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
# Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число більше попереднього на 2, та виведіть його значення.

In [6]:
matrix = np.matrix("0, 2, 4; 6, 8, 10; 12, 14, 16")
print(matrix)


[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [7]:
# Завдання 3: Створіть масив розміром 7x7, заповніть його випадковими цілими числами від -5 до 5 та виведіть його значення.

In [8]:
matrix = np.random.randint(-5, 6, (7, 7))
print(matrix)

[[-5 -4 -3 -1  5 -5  2]
 [-5 -1 -5 -2 -1  0  3]
 [ 5 -5  3  3  0 -5 -5]
 [-5 -3  4 -5 -2 -2  4]
 [-1  2  5  5 -1  2  5]
 [-2 -4  1  3  1  5 -3]
 [-3  4  1  3 -2  1  1]]


In [9]:
# Завдання 4: Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть максимальний елемент.

In [10]:
matrix = np.random.rand(6, 6)
print(matrix)
print(np.max(matrix))

[[0.69552023 0.17296683 0.63437523 0.39376198 0.05551085 0.85972405]
 [0.54645921 0.41041201 0.04055473 0.37499221 0.41585498 0.85749994]
 [0.7872125  0.22088391 0.29530331 0.63956813 0.03760762 0.79079432]
 [0.65717787 0.67792085 0.42232514 0.33400873 0.64018293 0.97393733]
 [0.42076135 0.58630315 0.80529914 0.70664124 0.06696423 0.05321488]
 [0.40851826 0.98632747 0.79557887 0.58385216 0.2311001  0.81876127]]
0.9863274721520975


In [11]:
# Завдання 5: Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [12]:
mas1 = np.random.randint(-5, 6, size = 4)
print("Mas 1: ", mas1)
mas2 = np.random.randint(-5, 6, size = 4)
print("Mas 2: ", mas2)
print("Mas 1 + Mas 2 = ", mas1 + mas2)
print("Mas 1 - Mas 2 = ", mas1 - mas2)
print("Mas 1 * Mas 2 = ", mas1 * mas2)

Mas 1:  [ 4  5  4 -2]
Mas 2:  [-5  1 -1 -4]
Mas 1 + Mas 2 =  [-1  6  3 -6]
Mas 1 - Mas 2 =  [9 4 5 2]
Mas 1 * Mas 2 =  [-20   5  -4   8]


In [13]:
# Завдання 6: Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [14]:
vect1 = np.random.randint(1, 21, size = 4)
print("Vector 1: ",vect1)
vect2 = np.random.randint(1, 21, size = 4)
print("Vector 2: ",vect2)
product = np.dot(vect1, vect2)
print("Добуток двох векторів = ", product)

Vector 1:  [ 3 14  4  2]
Vector 2:  [18  9 16  5]
Добуток двох векторів =  254


In [15]:
# Завдання 7: Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [16]:
matrix1 = np.random.randint(1, 11, (2, 3))
print("Matrix 1 : ")
print(matrix1)
matrix2 = np.random.randint(1, 11, (3, 3))
print("Matrix 2 : ")
print(matrix2)
matrixProduct = np.dot(matrix1, matrix2)
print("Результат множення матриць: ")
print(matrixProduct)

Matrix 1 : 
[[7 2 6]
 [6 8 5]]
Matrix 2 : 
[[ 8  5 10]
 [ 7  8  5]
 [ 2  2  4]]
Результат множення матриць: 
[[ 82  63 104]
 [114 104 120]]


In [17]:
# Завдання 8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [18]:
matrix = np.random.randint(1, 16, size = (3, 3))
print("Початкова матриця:")
print(matrix)
#Перевірка детермінанту: 
if np.linalg.det == 0:
    print("Матриця не має оберненої.")
else:
    invMatrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(invMatrix)

Початкова матриця:
[[ 3 12  1]
 [15  7 12]
 [ 1  4  1]]
Обернена матриця:
[[ 3.86792453e-01  7.54716981e-02 -1.29245283e+00]
 [ 2.83018868e-02 -1.88679245e-02  1.98113208e-01]
 [-5.00000000e-01  1.38777878e-18  1.50000000e+00]]


In [19]:
# Завдання 9: Створіть матрицю розміром 7x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [20]:
matrix = np.random.rand(4, 7)
print("Початкова матриця:")
print(matrix)
trMatrix = np.transpose(matrix)
print("Транспонована матриця:")
print(trMatrix)

Початкова матриця:
[[0.59014788 0.62806153 0.56239268 0.20378654 0.26688489 0.94914616
  0.42148264]
 [0.598562   0.89700358 0.65204523 0.35029854 0.84288865 0.90505872
  0.41591744]
 [0.81662673 0.77936921 0.4621561  0.55564084 0.59453695 0.3372649
  0.67075282]
 [0.83099965 0.79452233 0.67688558 0.59521292 0.67432436 0.26154852
  0.21104134]]
Транспонована матриця:
[[0.59014788 0.598562   0.81662673 0.83099965]
 [0.62806153 0.89700358 0.77936921 0.79452233]
 [0.56239268 0.65204523 0.4621561  0.67688558]
 [0.20378654 0.35029854 0.55564084 0.59521292]
 [0.26688489 0.84288865 0.59453695 0.67432436]
 [0.94914616 0.90505872 0.3372649  0.26154852]
 [0.42148264 0.41591744 0.67075282 0.21104134]]


In [21]:
# Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [22]:
matrix = np.random.randint(1, 11, (3, 4))
print("Початкова матриця:")
print(matrix)
vect = np.random.rand(4)
print("Вектор: ",vect)
prodMV = np.dot(matrix, vect)
print("Добуток матриці та вектора:")
print(prodMV)

Початкова матриця:
[[ 8  5  5  8]
 [ 4  8  1  6]
 [ 9  1 10  4]]
Вектор:  [0.64410991 0.99630119 0.46517186 0.10872878]
Добуток матриці та вектора:
[13.33007475 11.66439369 11.87992411]


In [23]:
# Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю.

In [24]:
matrix = np.random.rand(3, 2)
print("Матриця:")
print(matrix)
vect = np.random.rand(3)
print("Вектор: ",vect)
prodMV = np.dot(vect, matrix)
print("Добуток вектора та матриці:")
print(prodMV)

Матриця:
[[0.39406025 0.53241374]
 [0.98658969 0.95784677]
 [0.86758554 0.29742475]]
Вектор:  [0.62399205 0.62514725 0.12766084]
Добуток вектора та матриці:
[0.973411   0.96898671]


In [25]:
# Завдання 12: Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення першої матриці до другої (поелементне ділення).

In [26]:
matrix1 = np.random.randint(1, 11, (5, 5))
print("Матриця 1:")
print(matrix1)
matrix2 = np.random.randint(1, 11, (5, 5))
print("Матриця 2:")
print(matrix2)
divMatrix = matrix1/matrix2
print("Відношення матриць: ")
print(divMatrix)

Матриця 1:
[[ 1 10  6  7 10]
 [10  9  8  8  6]
 [ 8  1  5  4  8]
 [ 6  1  2  5  3]
 [ 3  7  7  5  2]]
Матриця 2:
[[ 4  3  4  3  4]
 [ 5  5  5  6  2]
 [ 3  4  8  7  9]
 [ 6  1 10 10  1]
 [ 6  3  8  6  9]]
Відношення матриць: 
[[0.25       3.33333333 1.5        2.33333333 2.5       ]
 [2.         1.8        1.6        1.33333333 3.        ]
 [2.66666667 0.25       0.625      0.57142857 0.88888889]
 [1.         1.         0.2        0.5        3.        ]
 [0.5        2.33333333 0.875      0.83333333 0.22222222]]


In [27]:
# Завдання 13: Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму їх елементів.

In [28]:
matrix1 = np.random.randint(1, 11, (5, 5))
print("Матриця 1:")
print(matrix1)
matrix2 = np.random.randint(1, 11, (5, 5))
print("Матриця 2:")
print(matrix2)
sumMatrix = matrix1 + matrix2
print("Сума матриць:")
print(sumMatrix)

Матриця 1:
[[ 8  2  1 10  7]
 [ 7  8  4  3  4]
 [ 1  7  2 10  5]
 [ 7  6  3  5  5]
 [ 4 10  6  9  8]]
Матриця 2:
[[ 8  7  9  1  7]
 [ 5  8  4  2  4]
 [ 6  7  1  4 10]
 [ 6  4 10  6  9]
 [ 5  2  2  5  3]]
Сума матриць:
[[16  9 10 11 14]
 [12 16  8  5  8]
 [ 7 14  3 14 15]
 [13 10 13 11 14]
 [ 9 12  8 14 11]]


In [29]:
# Завдання 14: Створіть матрицю розміром 8x8, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть добуток елементів матриці.

In [35]:
#matrix = np.random.randint(1, 101, (8, 8))
#print("Матриця:")
#print(matrix)
#elProd = np.prod(matrix)
#print("Добуток елементів матриці:")
#print(elProd)
#Через переповнення код вище показує результат 0, тому виконаний код нижче, котрий відрізняється лише розміром мматриці та елементами.
matrix = np.random.randint(1, 11, size=(3, 3))
print("Матриця:")
print(matrix)
product = np.prod(matrix)
print("Добуток елементів матриці: ", product)

Матриця:
[[ 5  6  6]
 [ 2  7  3]
 [10  9  1]]
Добуток елементів матриці:  680400


In [31]:
# Завдання 15: Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє арифметичне значення елементів кожного рядка матриці.

In [34]:
matrix = np.random.randint(-2, 3, (6, 6))
print("Матриця:")
print(matrix)
rowAvg = matrix.mean(axis=1)
colVector = rowAvg.reshape((-1, 1))
print("Вектор-стовпчик з середнім значенням елементів кожного рядка:")
print(colVector)

Матриця:
[[ 1 -1  2  1  2 -2]
 [ 2  0  0  2  2  0]
 [ 1 -1  2  0  0  2]
 [ 2 -2  0 -2  1 -2]
 [ 2  2  1  1  0  0]
 [ 1  1 -1 -2  0  0]]
Вектор-стовпчик з середнім значенням елементів кожного рядка:
[[ 0.5       ]
 [ 1.        ]
 [ 0.66666667]
 [-0.5       ]
 [ 1.        ]
 [-0.16666667]]


In [33]:
#Коментар: бібліотека NumPy надає можливості для виконання математиичних операцій з різноманітними масивами та матрицями і повністю задовольняє більшість необхідностей при роботі з ними.